"""
Run APHREH-ADSMap sensitivity analysis for the PM2.5 -> Respiratory pilot.

This script is a dedicated extension of the APHREH feasibility workflow.

It does NOT rebuild inputs.
It reuses:
    Dati/output/6-APHREH ADSMap/6.1-Prepared model inputs/PM25_Respiratory/

It writes outputs to separate folders, so the previous mini-sweep results are not overwritten.

Run modes:
    smoke_test:
        - one combination only: P75_L0
        - bootstrap_iterations = 20
        - sens_an_iterations = 5
        - used only to check that sensitivity analysis runs without errors

    final_bs100:
        - 12-combination sweep: P75/P85/P95 x L0/L3/L7/L14
        - bootstrap_iterations = 100
        - sens_an_iterations = 100
        - final recommended sensitivity run

    final_bs200:
        - same as final_bs100, but bootstrap_iterations = 200
        - heavier optional run
"""

from pathlib import Path
import shutil
import subprocess
import sys


# =============================================================================
# Run mode
# =============================================================================

# Start with smoke_test.
# If it works, change to:
RUN_MODE = "final_bs100"
#RUN_MODE = "smoke_test"


RUN_CONFIGS = {
    "smoke_test": {
        "output_label": "PM25_Respiratory_sensitivity_test",
        "single_combination": True,
        "bootstrap_iterations": 20,
        "sens_an_iterations": 5,
        "sensitivity_minmax": [-40, 100, 20],
    },
    "final_bs100": {
        "output_label": "PM25_Respiratory_sensitivity_bs100",
        "single_combination": False,
        "bootstrap_iterations": 100,
        "sens_an_iterations": 100,
        "sensitivity_minmax": [-40, 100, 20],
    },
    "final_bs200": {
        "output_label": "PM25_Respiratory_sensitivity_bs200",
        "single_combination": False,
        "bootstrap_iterations": 200,
        "sens_an_iterations": 100,
        "sensitivity_minmax": [-40, 100, 20],
    },
}


# =============================================================================
# Paths
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PILOT_LABEL = "PM25_Respiratory"

MODEL_SOURCE_DIR = PROJECT_ROOT / "external_models/APHREH-ADSMap_1.0.0"

INPUT_DIR = (
    PROJECT_ROOT
    / "Dati/output/6-APHREH ADSMap/6.1-Prepared model inputs"
    / PILOT_LABEL
)

CONFIG = RUN_CONFIGS[RUN_MODE]

OUTPUT_LABEL = CONFIG["output_label"]
SINGLE_COMBINATION_TEST = CONFIG["single_combination"]
BOOTSTRAP_ITERATIONS = CONFIG["bootstrap_iterations"]
SENS_AN_ITERATIONS = CONFIG["sens_an_iterations"]
SENSITIVITY_MINMAX = CONFIG["sensitivity_minmax"]

RESULTS_DIR = (
    PROJECT_ROOT
    / "Dati/output/6-APHREH ADSMap/6.2-Model outputs"
    / OUTPUT_LABEL
)

RUNTIME_DIR = (
    PROJECT_ROOT
    / "Dati/output/6-APHREH ADSMap/_runtime"
    / OUTPUT_LABEL
)


# =============================================================================
# Runtime preparation
# =============================================================================

def copy_model_to_runtime() -> None:
    """
    Copy the professor model into a local runtime directory.

    The original external_models/APHREH-ADSMap_1.0.0 folder is not modified.
    """
    if RUNTIME_DIR.exists():
        shutil.rmtree(RUNTIME_DIR)

    shutil.copytree(MODEL_SOURCE_DIR, RUNTIME_DIR)


def clean_previous_results() -> None:
    """
    Remove previous partial APHREH outputs for this sensitivity run.

    This avoids mixing results from failed/interrupted runs with the new run.
    """
    if RESULTS_DIR.exists():
        shutil.rmtree(RESULTS_DIR)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)


def patch_conf_py() -> None:
    """
    Replace runtime conf.py with a sensitivity-analysis configuration.
    """
    conf_path = RUNTIME_DIR / "conf.py"

    input_path = str(INPUT_DIR).replace("\\", "/") + "/"
    results_path = str(RESULTS_DIR).replace("\\", "/") + "/"

    # optmode_flag:
    #   0 = run one fixed parameter combination
    #   1 = run percentile-lag sweep
    optmode_flag_value = 0 if SINGLE_COMBINATION_TEST else 1

    conf_content = f'''import os
import pandas as pd
from datetime import timedelta

# =============================================================================
# APHREH-ADSMap runtime configuration
# Auto-generated by src/aphreh_adapter/run_aphreh_sensitivity.py
# Input pilot: {PILOT_LABEL}
# Output label: {OUTPUT_LABEL}
# Run mode: {RUN_MODE}
# =============================================================================

# PATHS

model_version = "v01/"
dspath = r"{input_path}"
respath = r"{results_path}"
outpath = respath + model_version

os.makedirs(respath, exist_ok=True)
os.makedirs(outpath, exist_ok=True)

yearly_folder = outpath + "Years/"
os.makedirs(yearly_folder, exist_ok=True)


# FLAGS

saveout = 1
dynawindow = 1

# optmode_flag:
#   0 = fixed single combination
#   1 = percentile-lag sweep
optmode_flag = {optmode_flag_value}

# Sensitivity analysis ON.
sensan_flag = 1

# Uncertainty analysis OFF for this project step.
uncertainty_flag = 0


# FIELD NAMES

exposure_db_name = "exposure_data.csv"
outcome_db_name = "outcome_data.csv"

# Reference analysis unit: municipality as BSA.
reference_geo_level = "BSA"
geoid = "BSA"
area_field = "BSA_AREA"

# Incidence multiplier.
# 100000 means incidence is computed per 100,000 inhabitants.
incidence_popmultiplier = 100000

# Source exposure unit: municipality as SRC.
source_geo_level = "SRC"
source_geoid = "SRC"

# Cross-grid intersection area field.
cross_area_field = "Area"


# PARAMETERS

exposure_nullvalues = [-1, -9999]
outcome_nullvalues = [-1, -9999]

years = [2016, 2017, 2018, 2019, 2023]
months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
zones = ["ALL"]

baseline_semiwindow = 15
semiwindow_max = 60

bootstrap_iterations = {BOOTSTRAP_ITERATIONS}

random_noise = 0.01
scale_exposure_threhsold = [0, 300]

# Uncertainty settings are kept defined even if uncertainty_flag = 0.
uncertainty_nvalues = 5
uncertainty_iterations = 100

# Sensitivity settings.
sensitivity_minmax = {SENSITIVITY_MINMAX}
sens_an_iterations = {SENS_AN_ITERATIONS}


# PARAMETER SETUP

if optmode_flag == 0:
    # Smoke test: one combination only.
    exposure_percentile_params = [0.75, 0.75, 0.05]
    lag_params = [0, 0, 1]

    exposure_percentile_list = [0.75]
    lag_list = [0]
    timelag_list = [timedelta(days=lag_list[0])]

if optmode_flag == 1:
    # Final focused sensitivity sweep:
    # 3 exposure thresholds x 4 lags = 12 combinations.
    exposure_percentile_params = [0.75, 0.95, 0.10]
    lag_params = [0, 14, 1]

    exposure_percentile_list = [0.75, 0.85, 0.95]
    lag_list = [0, 3, 7, 14]
    timelag_list = [timedelta(days=l) for l in lag_list]


# GLOBAL DATA STRUCTURES

exposure_percentile = 0
lag = 0
timelag = timedelta(days=0)
out_prefix = ""
process_string = ""
param_string = ""


class global_struct:
    def __init__(self):
        self.crossgrid = 0
        self.refgrid = 0
        self.exposure_grid = 0
        self.exposure = 0
        self.outcome = 0


class global_results:
    def __init__(self):
        self.marms = dict()
        self.wmarms = dict()
        self.marm_db = pd.DataFrame()
        self.wmarm_db = pd.DataFrame()
        self.max_wmarm = 0
        self.opt_params = ""

    def integrate_results(self, updated):
        for key in updated.marms.keys():
            self.marms[key] = updated.marms[key]
        for key in updated.wmarms.keys():
            self.wmarms[key] = updated.wmarms[key]

        self.max_wmarm = updated.max_wmarm
        self.opt_params = updated.opt_params

        for m_row in updated.marm_db.iterrows():
            self.marm_db.loc[m_row[0], :] = m_row[1]

        for wm_row in updated.wmarm_db.iterrows():
            self.wmarm_db.loc[wm_row[0], :] = wm_row[1]


class parametric_results:
    def __init__(self):
        self.marm = 0
        self.wmarm = 0
        self.stdeff_db = pd.DataFrame()
        self.out_index_df = pd.DataFrame()
        self.out_index_df_formatted = pd.DataFrame()
        self.cum_index_df = pd.DataFrame()
        self.cum_index_df_formatted = pd.DataFrame()


class parametric_struct:
    def __init__(self):
        self.th = 0
        self.lag = 0
        self.timelag = timedelta(days=0)
        self.exp_threshold = dict()
        self.exposed_days = []
        self.non_exposed_days = []
        self.incidence = pd.DataFrame()
        self.incidence_baseline = pd.DataFrame()
        self.yearly_ds = list()
        self.results = parametric_results()
        self.param_string = ""

    def set_paramstring(self):
        self.param_string = "EXP: " + str(self.th * 100) + "° perc - LAG: " + str(self.lag) + "\\t"


class yearly_struct:
    def __init__(self):
        self.year = 0
        self.expth = 0
        self.weights = pd.DataFrame()
        self.expdays = []
        self.nonexpdays = []
        self.yearly_index_df = pd.DataFrame()
        self.yearly_permutations_r = pd.DataFrame()
        self.yearly_permutations_p = pd.DataFrame()


# Required by post-processing / optimization code.
max_wmarm_ds = parametric_struct()


# Required because G_sensitivity_analysis.py imports these names.
sens_outprefix = ""
sens_exp_threshold = dict()
sens_exposed_days = []
sens_non_exposed_days = []
sens_incidence_base = pd.DataFrame()
sens_incidence_baseline = pd.DataFrame()
'''

    conf_path.write_text(conf_content, encoding="utf-8")


def patch_runtime_model_compatibility() -> None:
    """
    Apply small compatibility/runtime patches to the copied APHREH-ADSMap model.

    The original professor model is not modified.

    Patches:
        1. pandas compatibility:
           DataFrame.applymap() -> DataFrame.map()

        2. MAX_WMARM folder copy:
           The model saves parametric outputs under:
               outpath/Parametric/PXX_LYY/
           but identify_max_wmarm() searches:
               outpath/PXX_LYY/
           We patch it to search in the correct Parametric folder.

        3. Robust WMARM chart handling:
           Chart generation may fail with the reduced irregular lag grid.
           We save WMARM.csv and let the model complete.
    """

    # -------------------------------------------------------------------------
    # 1. Pandas compatibility patch in all runtime Python files
    # -------------------------------------------------------------------------
    for py_file in RUNTIME_DIR.glob("*.py"):
        text = py_file.read_text(encoding="utf-8")
        patched = text.replace(".applymap(", ".map(")

        if patched != text:
            py_file.write_text(patched, encoding="utf-8")
            print(f"Patched pandas compatibility in: {py_file.name}")

    # -------------------------------------------------------------------------
    # 2. Patch MAX_WMARM folder source path in E_compute_MARM.py
    # -------------------------------------------------------------------------
    marm_file = RUNTIME_DIR / "E_compute_MARM.py"

    if marm_file.exists():
        text = marm_file.read_text(encoding="utf-8")

        old_line = "source_folder = os.path.join(conf.outpath, max_wmarm_key)"
        new_line = "source_folder = os.path.join(conf.outpath, 'Parametric', max_wmarm_key)"

        patched = text.replace(old_line, new_line)

        if patched != text:
            marm_file.write_text(patched, encoding="utf-8")
            print("Patched MAX_WMARM source folder path in: E_compute_MARM.py")

    # -------------------------------------------------------------------------
    # 3. Robust WMARM chart handling
    # -------------------------------------------------------------------------
    main_file = RUNTIME_DIR / "main.py"

    if main_file.exists():
        text = main_file.read_text(encoding="utf-8")

        old_line = "generate_chart(updated_main_res.wmarm_db)"

        new_block = """try:
    generate_chart(updated_main_res.wmarm_db)
except Exception as exc:
    import os
    plot_dir = os.path.join(conf.outpath, 'PLOT')
    os.makedirs(plot_dir, exist_ok=True)

    updated_main_res.wmarm_db.index.rename(
        'Exposure Threshold [%] VS Time Lag [days]',
        inplace=True
    )
    updated_main_res.wmarm_db.to_csv(os.path.join(plot_dir, 'WMARM.csv'))

    print('WMARM chart generation failed, but WMARM.csv was saved.')
    print(f'Chart error: {exc}')"""

        patched = text.replace(old_line, new_block)

        if patched != text:
            main_file.write_text(patched, encoding="utf-8")
            print("Patched robust WMARM chart handling in: main.py")


# =============================================================================
# Model execution
# =============================================================================

def run_model() -> None:
    """
    Run APHREH-ADSMap main.py inside the runtime directory.
    """
    completed = subprocess.run(
        [sys.executable, "main.py"],
        cwd=RUNTIME_DIR,
        text=True,
    )

    if completed.returncode != 0:
        raise RuntimeError(f"APHREH-ADSMap failed with exit code {completed.returncode}.")


def main() -> None:
    print("=" * 100)
    print("Running APHREH-ADSMap sensitivity analysis")
    print(f"Input pilot: {PILOT_LABEL}")
    print(f"Run mode: {RUN_MODE}")
    print(f"Output label: {OUTPUT_LABEL}")
    print(f"Single-combination test mode: {SINGLE_COMBINATION_TEST}")
    print(f"Bootstrap iterations: {BOOTSTRAP_ITERATIONS}")
    print(f"Sensitivity iterations: {SENS_AN_ITERATIONS}")
    print(f"Sensitivity min/max/step: {SENSITIVITY_MINMAX}")
    print("=" * 100)

    if not MODEL_SOURCE_DIR.exists():
        raise FileNotFoundError(f"APHREH model folder not found: {MODEL_SOURCE_DIR}")

    if not INPUT_DIR.exists():
        raise FileNotFoundError(
            f"Input directory not found: {INPUT_DIR}\n"
            "Run prepare_aphreh_inputs.py first."
        )

    clean_previous_results()
    copy_model_to_runtime()
    patch_conf_py()
    patch_runtime_model_compatibility()
    run_model()

    print("\nAPHREH-ADSMap sensitivity run completed.")
    print(f"Results folder: {RESULTS_DIR.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()