"""
Summarize APHREH-ADSMap sensitivity run outputs into project-readable tables.

This script does NOT rerun APHREH.

Input:
    Dati/output/6-APHREH ADSMap/6.2-Model outputs/PM25_Respiratory_sensitivity_bs100/v01/

Output:
    Dati/output/6-APHREH ADSMap/6.3-Output summaries/PM25_Respiratory_sensitivity_bs100/

Generated files:
    aphreh_sensitivity_municipality_summary.csv
    aphreh_sensitivity_area_summary.csv
    aphreh_sensitivity_model_summary.csv
    aphreh_sensitivity_parameter_sweep_summary.csv
    aphreh_sensitivity_exposure_thresholds.csv

Run:
    PM2.5 -> Respiratory acute events
    12-combination focused sweep
    bootstrap_iterations = 100
    sensitivity analysis = ON
"""

from pathlib import Path
import re
import pandas as pd


# =============================================================================
# Configuration
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

RUN_LABEL = "PM25_Respiratory_sensitivity_bs100"

APHREH_OUTPUT_ROOT = (
    PROJECT_ROOT
    / "Dati/output/6-APHREH ADSMap/6.2-Model outputs"
    / RUN_LABEL
    / "v01"
)

PARAMETRIC_DIR = APHREH_OUTPUT_ROOT / "Parametric"

STUDY_MUNICIPALITIES_PATH = (
    PROJECT_ROOT
    / "Dati/output/2-Health data/2.2-Health event aggregation/study_area_municipalities.csv"
)

SUMMARY_OUTPUT_DIR = (
    PROJECT_ROOT
    / "Dati/output/6-APHREH ADSMap/6.3-Output summaries"
    / RUN_LABEL
)


# =============================================================================
# Helpers
# =============================================================================

def read_scalar_txt(path: Path, label: str) -> float:
    """
    Read scalar files like:
        MARM: 5.01e-05
        WMARM: 4.17e-05
    """
    text = path.read_text(encoding="utf-8").strip()
    value = text.replace(label, "").replace(":", "").strip()
    return float(value)


def parse_parameter_folder_name(folder_name: str) -> tuple[int, int]:
    """
    Parse folder names like:
        P75_L0
        P95_L14

    Returns:
        exposure_percentile, lag_days
    """
    match = re.match(r"P(\d+)_L(\d+)", folder_name)

    if match is None:
        raise ValueError(f"Cannot parse parameter folder name: {folder_name}")

    percentile = int(match.group(1))
    lag_days = int(match.group(2))

    return percentile, lag_days


def detect_max_wmarm_folder() -> Path:
    """
    Detect the MAX_WMARM_* folder generated by APHREH.
    """
    folders = sorted(APHREH_OUTPUT_ROOT.glob("MAX_WMARM_*"))

    if not folders:
        raise FileNotFoundError(
            f"No MAX_WMARM_* folder found in: {APHREH_OUTPUT_ROOT}"
        )

    if len(folders) > 1:
        print("Warning: multiple MAX_WMARM folders found. Using the most recent one.")
        folders = sorted(folders, key=lambda p: p.stat().st_mtime)

    return folders[-1]


def load_study_municipalities() -> pd.DataFrame:
    """
    Load municipality metadata and keep BSA-compatible columns.
    """
    study = pd.read_csv(STUDY_MUNICIPALITIES_PATH, sep=";", low_memory=False)

    required = ["Area", "PROV", "Municipality", "Municipality_code"]
    missing = [col for col in required if col not in study.columns]

    if missing:
        raise ValueError(f"Missing columns in study municipalities file: {missing}")

    study = study.copy()
    study["BSA"] = study["Municipality_code"].astype(int)

    study = study[["BSA", "Municipality", "Area", "PROV"]].copy()
    study = study.rename(columns={"PROV": "Province"})

    return study


def load_aphreh_results(best_param_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load APHREH index outputs for the selected MAX_WMARM parameter.
    """
    index_raw_path = best_param_dir / "index_raw.csv"
    index_cumulated_path = best_param_dir / "index_cumulated_raw.csv"

    if not index_raw_path.exists():
        raise FileNotFoundError(f"Missing file: {index_raw_path}")

    if not index_cumulated_path.exists():
        raise FileNotFoundError(f"Missing file: {index_cumulated_path}")

    index_raw = pd.read_csv(index_raw_path)
    index_cumulated = pd.read_csv(index_cumulated_path)

    index_raw["BSA"] = index_raw["BSA"].astype(int)
    index_cumulated["BSA"] = index_cumulated["BSA"].astype(int)

    return index_raw, index_cumulated


def build_parameter_sweep_summary() -> pd.DataFrame:
    """
    Read MARM and WMARM for all parameter combinations under Parametric/.
    """
    if not PARAMETRIC_DIR.exists():
        raise FileNotFoundError(f"Missing Parametric folder: {PARAMETRIC_DIR}")

    rows = []

    for folder in sorted(PARAMETRIC_DIR.iterdir()):
        if not folder.is_dir():
            continue

        folder_name = folder.name

        try:
            percentile, lag_days = parse_parameter_folder_name(folder_name)
        except ValueError:
            continue

        marm_path = folder / "marm_value.txt"
        wmarm_path = folder / "wmarm_value.txt"

        if not marm_path.exists() or not wmarm_path.exists():
            continue

        rows.append(
            {
                "Parameter_folder": folder_name,
                "Exposure_percentile": percentile,
                "Lag_days": lag_days,
                "MARM": read_scalar_txt(marm_path, "MARM"),
                "WMARM": read_scalar_txt(wmarm_path, "WMARM"),
            }
        )

    summary = pd.DataFrame(rows)

    if summary.empty:
        raise ValueError("No parameter sweep results found.")

    summary = summary.sort_values("WMARM", ascending=False).reset_index(drop=True)
    summary.insert(0, "WMARM_rank", range(1, len(summary) + 1))

    return summary


def build_municipality_summary(
    study: pd.DataFrame,
    index_raw: pd.DataFrame,
    index_cumulated: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build one row per municipality.

    Main fields:
        INDEX_MEDIAN:
            multi-year median APHREH index.

        INDEX_Q25 / INDEX_Q75:
            interquartile range across selected years.

        CI_LOW_MEDIAN / CI_HIGH_MEDIAN:
            median lower/upper confidence bounds.

        AVG_STDEFF:
            averaged standardized effect used by MARM/WMARM.
    """
    keep_cumulated = [
        "BSA",
        "INDEX_MEDIAN",
        "INDEX_Q25",
        "INDEX_Q75",
        "INDEX_IQR",
        "CI_LOW_MEDIAN",
        "CI_HIGH_MEDIAN",
        "AVG_STDEFF",
    ]

    missing = [col for col in keep_cumulated if col not in index_cumulated.columns]

    if missing:
        raise ValueError(f"Missing columns in index_cumulated_raw.csv: {missing}")

    municipality_summary = study.merge(
        index_cumulated[keep_cumulated],
        on="BSA",
        how="left",
        validate="one_to_one",
    )

    year_index_columns = [
        col for col in index_raw.columns
        if (col.endswith("INDEX") or col.endswith("STDEFF"))
        and col != "AVG_STDEFF"
    ]

    year_values = index_raw[["BSA"] + year_index_columns].copy()

    municipality_summary = municipality_summary.merge(
        year_values,
        on="BSA",
        how="left",
        validate="one_to_one",
    )

    municipality_summary = municipality_summary.sort_values(
        by="AVG_STDEFF",
        ascending=False,
    ).reset_index(drop=True)

    return municipality_summary


def build_area_summary(municipality_summary: pd.DataFrame) -> pd.DataFrame:
    """
    Summarize municipality-level APHREH outputs by Agricultural/Industrial area.
    """
    area_summary = (
        municipality_summary
        .groupby("Area")
        .agg(
            n_municipalities=("BSA", "count"),
            mean_index_median=("INDEX_MEDIAN", "mean"),
            median_index_median=("INDEX_MEDIAN", "median"),
            min_index_median=("INDEX_MEDIAN", "min"),
            max_index_median=("INDEX_MEDIAN", "max"),
            mean_avg_stdeff=("AVG_STDEFF", "mean"),
            median_avg_stdeff=("AVG_STDEFF", "median"),
            min_avg_stdeff=("AVG_STDEFF", "min"),
            max_avg_stdeff=("AVG_STDEFF", "max"),
        )
        .reset_index()
    )

    return area_summary


def build_model_summary(
    best_param_dir: Path,
    parameter_sweep_summary: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build one-row model summary for the final sensitivity run.
    """
    best_folder_name = best_param_dir.name.replace("MAX_WMARM_", "")
    best_percentile, best_lag = parse_parameter_folder_name(best_folder_name)

    best_row = parameter_sweep_summary.loc[
        parameter_sweep_summary["Parameter_folder"] == best_folder_name
    ]

    if best_row.empty:
        marm = read_scalar_txt(best_param_dir / "marm_value.txt", "MARM")
        wmarm = read_scalar_txt(best_param_dir / "wmarm_value.txt", "WMARM")
    else:
        marm = float(best_row["MARM"].iloc[0])
        wmarm = float(best_row["WMARM"].iloc[0])

    model_summary = pd.DataFrame(
        [
            {
                "Run": RUN_LABEL,
                "Selected_parameter_folder": best_param_dir.name,
                "Selected_parameter": best_folder_name,
                "Pollutant": "PM2.5",
                "Outcome": "Respiratory",
                "Exposure_percentile": best_percentile,
                "Lag_days": best_lag,
                "N_parameter_combinations": len(parameter_sweep_summary),
                "Bootstrap_iterations": 100,
                "Sensitivity_analysis": "ON",
                "Sensitivity_range": "-40% to +100%, step 20%",
                "MARM": marm,
                "WMARM": wmarm,
                "Interpretation_note": (
                    "Final APHREH-ADSMap PM2.5-respiratory sensitivity run. "
                    "The selected parameter maximizes WMARM within the focused "
                    "12-combination grid, using 100 bootstrap iterations and "
                    "sensitivity analysis enabled."
                ),
            }
        ]
    )

    return model_summary


def load_exposure_thresholds() -> pd.DataFrame:
    """
    Load yearly exposure thresholds if available.
    """
    path = APHREH_OUTPUT_ROOT / "Years/exposure_thresholds.csv"

    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")

    thresholds = pd.read_csv(path)

    return thresholds


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    print("=" * 100)
    print("Summarizing APHREH-ADSMap sensitivity outputs")
    print(f"Run: {RUN_LABEL}")
    print("=" * 100)

    if not APHREH_OUTPUT_ROOT.exists():
        raise FileNotFoundError(
            f"APHREH output root not found: {APHREH_OUTPUT_ROOT}"
        )

    SUMMARY_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    best_param_dir = detect_max_wmarm_folder()
    parameter_sweep_summary = build_parameter_sweep_summary()

    study = load_study_municipalities()
    index_raw, index_cumulated = load_aphreh_results(best_param_dir)

    municipality_summary = build_municipality_summary(
        study=study,
        index_raw=index_raw,
        index_cumulated=index_cumulated,
    )

    area_summary = build_area_summary(municipality_summary)
    model_summary = build_model_summary(best_param_dir, parameter_sweep_summary)
    exposure_thresholds = load_exposure_thresholds()

    municipality_summary_path = SUMMARY_OUTPUT_DIR / "aphreh_sensitivity_municipality_summary.csv"
    area_summary_path = SUMMARY_OUTPUT_DIR / "aphreh_sensitivity_area_summary.csv"
    model_summary_path = SUMMARY_OUTPUT_DIR / "aphreh_sensitivity_model_summary.csv"
    parameter_sweep_path = SUMMARY_OUTPUT_DIR / "aphreh_sensitivity_parameter_sweep_summary.csv"
    thresholds_path = SUMMARY_OUTPUT_DIR / "aphreh_sensitivity_exposure_thresholds.csv"

    municipality_summary.to_csv(municipality_summary_path, sep=";", index=False)
    area_summary.to_csv(area_summary_path, sep=";", index=False)
    model_summary.to_csv(model_summary_path, sep=";", index=False)
    parameter_sweep_summary.to_csv(parameter_sweep_path, sep=";", index=False)
    exposure_thresholds.to_csv(thresholds_path, sep=";", index=False)

    print("\nGenerated summary files:")
    for path in [
        municipality_summary_path,
        area_summary_path,
        model_summary_path,
        parameter_sweep_path,
        thresholds_path,
    ]:
        print(f"  - {path.relative_to(PROJECT_ROOT)}")

    print("\nModel summary:")
    print(model_summary.to_string(index=False))

    print("\nTop parameter combinations by WMARM:")
    print(parameter_sweep_summary.head(12).to_string(index=False))

    print("\nArea summary for selected MAX_WMARM parameter:")
    print(area_summary.to_string(index=False))

    print("\nTop 10 municipalities by AVG_STDEFF:")
    print(
        municipality_summary[
            [
                "BSA",
                "Municipality",
                "Area",
                "Province",
                "INDEX_MEDIAN",
                "CI_LOW_MEDIAN",
                "CI_HIGH_MEDIAN",
                "AVG_STDEFF",
            ]
        ]
        .head(10)
        .to_string(index=False)
    )

    print("\nBottom 10 municipalities by AVG_STDEFF:")
    print(
        municipality_summary[
            [
                "BSA",
                "Municipality",
                "Area",
                "Province",
                "INDEX_MEDIAN",
                "CI_LOW_MEDIAN",
                "CI_HIGH_MEDIAN",
                "AVG_STDEFF",
            ]
        ]
        .tail(10)
        .to_string(index=False)
    )

    print("\nDone.")


if __name__ == "__main__":
    main()